# Generated by Django 4.2.5 on 2024-01-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='empty')),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('family', 'Family'), ('work', 'Work'), ('personal', 'Personal'), ('Others', 'Others')], default='unknown', max_length=50)),
                ('first_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Incompleted', max_length=30)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
